"""Seed the database with baseline development data.

Usage:
    python -m backend.scripts.seed

Reuses the project's existing components rather than reimplementing them:
- `backend.database.session.async_session_factory` for the DB connection
- `backend.database.models.*` (ORM models) and `backend.database.enums.*`
- `backend.auth.hashing.hash_password` for password hashing

Idempotent: if the admin user (`_ADMIN_EMAIL`) already exists, the script
prints a message and exits without touching the database further. Combined
with `users.email` being UNIQUE at the schema level, this also means a race
between two concurrent runs fails safely (the second run's insert violates
the unique constraint and the whole transaction rolls back) rather than
producing duplicate rows.

`agent_runs`, `approval_requests`, and `audit_logs` are intentionally left
empty — they're operational data generated by using the application, not
fixtures. `knowledge_articles` is seeded, unlike those three: it's reference
content (`backend.tools.knowledge_base.KnowledgeBaseSearchTool` reads it to
ground CrewAI specialist responses), not something usage generates, so an
empty table would just mean every agent response is ungrounded rather than
demonstrating the real retrieval path.
"""

from __future__ import annotations

import asyncio
import os
import sys
from typing import TypedDict

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.auth.hashing import hash_password
from backend.config.settings import get_settings
from backend.core.logging import configure_logging, get_logger
from backend.database.enums import CustomerTier, TicketPriority, TicketStatus, UserRole
from backend.database.models.customer import Customer
from backend.database.models.knowledge_article import KnowledgeArticle
from backend.database.models.ticket import Ticket
from backend.database.models.user import User
from backend.database.session import async_session_factory

logger = get_logger(__name__)

# --------------------------------------------------------------------------
# Seed data
#
# Plain data (TypedDicts), kept separate from the functions that write it,
# so the dataset can be scanned/edited without wading through ORM code.
# --------------------------------------------------------------------------


class _UserSeed(TypedDict):
    full_name: str
    email: str
    password: str  # dev-only plaintext; hashed before it ever reaches the DB
    role: UserRole


class _CustomerSeed(TypedDict):
    name: str
    email: str
    company: str
    tier: CustomerTier


class _TicketSeed(TypedDict):
    customer_index: int  # index into _CUSTOMERS
    subject: str
    description: str
    priority: TicketPriority
    status: TicketStatus
    assigned_to: str | None  # agent email, or None for an unassigned ticket
    ai_summary: str | None


class _KnowledgeArticleSeed(TypedDict):
    category: str  # matches backend.graph.state.TicketCategory's values as a plain string
    title: str
    content: str


_ADMIN_EMAIL = "admin@supportops.ai"

_USERS: list[_UserSeed] = [
    {
        "full_name": "Admin",
        "email": _ADMIN_EMAIL,
        "password": "AdminPass123!",
        "role": UserRole.ADMIN,
    },
    {
        "full_name": "Supervisor",
        "email": "supervisor@supportops.ai",
        "password": "SupervisorPass123!",
        "role": UserRole.SUPERVISOR,
    },
    {
        "full_name": "Agent One",
        "email": "agent1@supportops.ai",
        "password": "AgentOnePass123!",
        "role": UserRole.AGENT,
    },
    {
        "full_name": "Agent Two",
        "email": "agent2@supportops.ai",
        "password": "AgentTwoPass123!",
        "role": UserRole.AGENT,
    },
]

_CUSTOMERS: list[_CustomerSeed] = [
    {
        "name": "Jane Doe",
        "email": "jane.doe@acme.example.com",
        "company": "Acme Corporation",
        "tier": CustomerTier.ENTERPRISE,
    },
    {
        "name": "John Smith",
        "email": "john.smith@globex.example.com",
        "company": "Globex Corporation",
        "tier": CustomerTier.PREMIUM,
    },
    {
        "name": "Bruce Wayne",
        "email": "bruce.wayne@wayne.example.com",
        "company": "Wayne Enterprises",
        "tier": CustomerTier.ENTERPRISE,
    },
    {
        "name": "Tony Stark",
        "email": "tony.stark@stark.example.com",
        "company": "Stark Industries",
        "tier": CustomerTier.ENTERPRISE,
    },
    {
        "name": "Alice Johnson",
        "email": "alice.johnson@umbrella.example.com",
        "company": "Umbrella Corporation",
        "tier": CustomerTier.STANDARD,
    },
]

# NOTE: docs/database_schema.md's TicketStatus is
# NEW/TRIAGED/ASSIGNED/DRAFTED/APPROVAL_REQUIRED/APPROVED/SENT/CLOSED and
# TicketPriority is LOW/MEDIUM/HIGH/URGENT — the schema's actual enums
# (backend/database/enums.py) are reused here rather than the generic
# "Open/Pending/In Progress/Resolved" and "Critical" labels, so seeded rows
# stay valid against the real ENUM columns.
_TICKETS: list[_TicketSeed] = [
    {
        "customer_index": 0,
        "subject": "Cannot log into account",
        "description": (
            "Customer reports repeated 'invalid credentials' errors despite "
            "resetting their password twice today."
        ),
        "priority": TicketPriority.HIGH,
        "status": TicketStatus.NEW,
        "assigned_to": None,
        "ai_summary": None,
    },
    {
        "customer_index": 0,
        "subject": "Billing discrepancy on invoice #4521",
        "description": (
            "Customer was charged twice for the March subscription renewal "
            "and is requesting a refund."
        ),
        "priority": TicketPriority.MEDIUM,
        "status": TicketStatus.TRIAGED,
        "assigned_to": None,
        "ai_summary": None,
    },
    {
        "customer_index": 0,
        "subject": "Feature request: bulk CSV export",
        "description": (
            "Customer wants to export all tickets and customer records as a "
            "single CSV file for internal reporting."
        ),
        "priority": TicketPriority.LOW,
        "status": TicketStatus.CLOSED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": (
            "Confirmed bulk export is on the public roadmap; customer "
            "notified and ticket closed as acknowledged."
        ),
    },
    {
        "customer_index": 1,
        "subject": "API returning intermittent 500 errors",
        "description": (
            "Customer's integration receives sporadic 500 Internal Server "
            "Error responses from the /v1/tickets endpoint, roughly 1 in 20 "
            "requests."
        ),
        "priority": TicketPriority.URGENT,
        "status": TicketStatus.ASSIGNED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 1,
        "subject": "Password reset email not received",
        "description": (
            "Customer requested a password reset three times but has not "
            "received the email; spam folder confirmed empty."
        ),
        "priority": TicketPriority.MEDIUM,
        "status": TicketStatus.DRAFTED,
        "assigned_to": "agent2@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 1,
        "subject": "Upgrade subscription tier",
        "description": (
            "Customer wants to move from the Premium plan to Enterprise and "
            "asked about migration steps."
        ),
        "priority": TicketPriority.LOW,
        "status": TicketStatus.NEW,
        "assigned_to": None,
        "ai_summary": None,
    },
    {
        "customer_index": 2,
        "subject": "Data export missing records",
        "description": (
            "Customer's nightly data export is missing roughly 200 records "
            "compared to the in-app dashboard count."
        ),
        "priority": TicketPriority.HIGH,
        "status": TicketStatus.APPROVAL_REQUIRED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 2,
        "subject": "SSO integration broken after update",
        "description": (
            "Customer can no longer log in via their SAML identity provider "
            "after last night's platform update."
        ),
        "priority": TicketPriority.URGENT,
        "status": TicketStatus.TRIAGED,
        "assigned_to": None,
        "ai_summary": None,
    },
    {
        "customer_index": 2,
        "subject": "Dashboard loading slowly",
        "description": (
            "Customer reports the analytics dashboard takes over 30 seconds "
            "to load for accounts with large ticket volumes."
        ),
        "priority": TicketPriority.MEDIUM,
        "status": TicketStatus.ASSIGNED,
        "assigned_to": "agent2@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 3,
        "subject": "Unable to add new team members",
        "description": (
            "Customer receives a generic 'something went wrong' error when "
            "inviting new teammates from the admin panel."
        ),
        "priority": TicketPriority.MEDIUM,
        "status": TicketStatus.APPROVED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": (
            "Root cause identified as a seat-limit check bug; fix scheduled, "
            "customer informed of timeline."
        ),
    },
    {
        "customer_index": 3,
        "subject": "Incorrect usage metrics displayed",
        "description": (
            "Customer's usage dashboard shows zero API calls despite active "
            "daily traffic confirmed in server logs."
        ),
        "priority": TicketPriority.LOW,
        "status": TicketStatus.SENT,
        "assigned_to": "agent2@supportops.ai",
        "ai_summary": (
            "Metrics pipeline delay explained to customer; dashboard "
            "back-filled and confirmed correct."
        ),
    },
    {
        "customer_index": 3,
        "subject": "Critical outage affecting all users",
        "description": (
            "Customer's entire team is unable to access the platform; "
            "status page shows no reported incident."
        ),
        "priority": TicketPriority.URGENT,
        "status": TicketStatus.ASSIGNED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 4,
        "subject": "Request for GDPR data deletion",
        "description": (
            "Customer is formally requesting deletion of all personal data "
            "associated with their account under GDPR Article 17."
        ),
        "priority": TicketPriority.HIGH,
        "status": TicketStatus.APPROVAL_REQUIRED,
        "assigned_to": "agent2@supportops.ai",
        "ai_summary": None,
    },
    {
        "customer_index": 4,
        "subject": "Typo in confirmation email",
        "description": (
            "Customer flagged a typo ('recieved' instead of 'received') in "
            "the automated ticket confirmation email template."
        ),
        "priority": TicketPriority.LOW,
        "status": TicketStatus.CLOSED,
        "assigned_to": "agent1@supportops.ai",
        "ai_summary": "Typo corrected in the email template; no further action needed.",
    },
    {
        "customer_index": 4,
        "subject": "Webhook delivery failures",
        "description": (
            "Customer's configured webhook endpoint has not received any "
            "events in the last 48 hours despite ticket activity."
        ),
        "priority": TicketPriority.HIGH,
        "status": TicketStatus.NEW,
        "assigned_to": None,
        "ai_summary": None,
    },
]

_KNOWLEDGE_ARTICLES: list[_KnowledgeArticleSeed] = [
    {
        "category": "billing",
        "title": "Refund Policy",
        "content": (
            "Refunds for duplicate or erroneous charges are issued to the original "
            "payment method within 5-7 business days. Subscription refunds for "
            "cancellations made within 14 days of renewal are prorated automatically."
        ),
    },
    {
        "category": "billing",
        "title": "Understanding Your Invoice",
        "content": (
            "Each invoice lists the billing period, plan tier, prorated charges for "
            "mid-cycle upgrades, and any applicable tax. Line items marked 'usage' "
            "reflect metered API calls beyond the plan's included quota."
        ),
    },
    {
        "category": "billing",
        "title": "Upgrading or Downgrading Your Plan",
        "content": (
            "Plan changes take effect immediately; upgrades are billed pro-rata for "
            "the remainder of the current cycle, downgrades take effect at the next "
            "renewal so no service is lost mid-cycle."
        ),
    },
    {
        "category": "technical",
        "title": "Troubleshooting Login Failures",
        "content": (
            "Repeated 'invalid credentials' errors after a password reset usually "
            "mean a cached session token; ask the customer to fully sign out, clear "
            "cookies for the app domain, and sign back in with the new password."
        ),
    },
    {
        "category": "technical",
        "title": "Diagnosing Intermittent API 500 Errors",
        "content": (
            "Sporadic 500s on a small percentage of requests are most often caused "
            "by a transient upstream timeout; check the request ID against the API "
            "status page and retry with exponential backoff before escalating."
        ),
    },
    {
        "category": "technical",
        "title": "SSO / SAML Login Issues After a Platform Update",
        "content": (
            "After a platform update, SAML logins can fail if the identity "
            "provider's cached metadata is stale; ask the customer's admin to "
            "re-fetch the SP metadata URL and re-upload it to their IdP."
        ),
    },
    {
        "category": "account",
        "title": "Adding and Removing Team Members",
        "content": (
            "New teammates are invited from Settings > Team > Invite. A generic "
            "'something went wrong' error when inviting usually means the "
            "account has hit its seat limit -- check the plan's seat count first."
        ),
    },
    {
        "category": "account",
        "title": "GDPR Data Deletion Requests",
        "content": (
            "A formal Article 17 deletion request must be routed to the privacy "
            "team and requires supervisor approval before execution; acknowledge "
            "receipt to the customer and confirm the 30-day completion window."
        ),
    },
    {
        "category": "account",
        "title": "Resetting a Forgotten Password",
        "content": (
            "If a password-reset email never arrives, confirm the address on file "
            "is correct and ask the customer to check spam; the reset link expires "
            "after 1 hour, so a fresh request is needed if it was delayed."
        ),
    },
    {
        "category": "general",
        "title": "Support Response Time Expectations",
        "content": (
            "Standard-tier tickets are addressed within 2 business days, Premium "
            "within 1 business day, and Enterprise within 4 business hours; urgent "
            "priority tickets are triaged immediately regardless of tier."
        ),
    },
    {
        "category": "general",
        "title": "Requesting a New Feature",
        "content": (
            "Feature requests are logged to the product roadmap for review; there "
            "is no guaranteed timeline, but customers can be told a request has "
            "been recorded and to watch the changelog for updates."
        ),
    },
]


# --------------------------------------------------------------------------
# Seeding logic
# --------------------------------------------------------------------------


async def _already_seeded(session: AsyncSession) -> bool:
    """Idempotency check: the admin user's existence is the seed marker."""
    result = await session.execute(select(User.id).where(User.email == _ADMIN_EMAIL))
    return result.scalar_one_or_none() is not None


async def _knowledge_articles_already_seeded(session: AsyncSession) -> bool:
    """A separate idempotency check, deliberately independent of
    `_already_seeded`: `knowledge_articles` was added after this script's
    other fixtures, so a deployment that already ran `seed()` (and would
    otherwise skip everything via the admin-user check) still gets these
    backfilled the next time the script runs."""
    result = await session.execute(select(KnowledgeArticle.id).limit(1))
    return result.scalar_one_or_none() is not None


async def _seed_users(session: AsyncSession) -> dict[str, User]:
    """Create the default users; return them keyed by email for lookup."""
    logger.info("Creating users...")
    users: dict[str, User] = {}
    for spec in _USERS:
        user = User(
            email=spec["email"],
            password_hash=hash_password(spec["password"]),
            full_name=spec["full_name"],
            role=spec["role"],
            is_active=True,
        )
        session.add(user)
        users[spec["email"]] = user
    await session.flush()  # assign PKs so tickets can reference them below
    return users


async def _seed_customers(session: AsyncSession) -> list[Customer]:
    """Create the demo customers, in `_CUSTOMERS` order."""
    logger.info("Creating customers...")
    customers = [
        Customer(
            name=spec["name"],
            email=spec["email"],
            company=spec["company"],
            tier=spec["tier"],
        )
        for spec in _CUSTOMERS
    ]
    session.add_all(customers)
    await session.flush()
    return customers


async def _seed_tickets(
    session: AsyncSession,
    customers: list[Customer],
    users: dict[str, User],
) -> None:
    """Create the demo tickets, wired to `customers`/`users` via relationships."""
    logger.info("Creating tickets...")
    tickets = [
        Ticket(
            customer=customers[spec["customer_index"]],
            assigned_agent=users[spec["assigned_to"]] if spec["assigned_to"] else None,
            subject=spec["subject"],
            description=spec["description"],
            priority=spec["priority"],
            status=spec["status"],
            ai_summary=spec["ai_summary"],
        )
        for spec in _TICKETS
    ]
    session.add_all(tickets)
    await session.flush()


async def _seed_knowledge_articles(session: AsyncSession) -> None:
    """Create the demo knowledge-base articles `KnowledgeBaseSearchTool` retrieves."""
    logger.info("Creating knowledge articles...")
    articles = [
        KnowledgeArticle(
            category=spec["category"],
            title=spec["title"],
            content=spec["content"],
        )
        for spec in _KNOWLEDGE_ARTICLES
    ]
    session.add_all(articles)
    await session.flush()


async def seed() -> None:
    """Seed the database with baseline development data, idempotently.

    Runs as a single transaction: either every row commits, or (on any
    exception) nothing does.
    """
    settings = get_settings()
    if settings.environment == "production" and not os.environ.get("ALLOW_SEED_IN_PRODUCTION"):
        logger.error(
            "Refusing to run the dev seed script against a production "
            "database (ENVIRONMENT=production). Set "
            "ALLOW_SEED_IN_PRODUCTION=1 to override."
        )
        sys.exit(1)

    async with async_session_factory() as session:
        try:
            already_seeded = await _already_seeded(session)
            if already_seeded:
                logger.info("Database already seeded (users/customers/tickets). Skipping those.")
            else:
                users = await _seed_users(session)
                customers = await _seed_customers(session)
                await _seed_tickets(session, customers, users)

            if await _knowledge_articles_already_seeded(session):
                logger.info("Knowledge articles already seeded. Skipping.")
            else:
                await _seed_knowledge_articles(session)

            await session.commit()
            logger.info("Database seeded successfully.")
        except Exception:
            logger.error("Seeding failed; rolling back transaction.", exc_info=True)
            await session.rollback()
            raise


def main() -> None:
    """Entry point for `python -m backend.scripts.seed`."""
    configure_logging()
    asyncio.run(seed())


if __name__ == "__main__":
    main()
