"""Node implementations for the support workflow graph.

Every node is a plain function `(WorkflowState) -> dict` — the LangGraph
convention of returning a partial state update rather than the full state.
Each one is a deterministic placeholder wired to the correct field(s) of
`WorkflowState` so the graph topology in `backend/graph/workflow.py` never
has to change when a placeholder is replaced with real logic:

- `classify_ticket_node` will be replaced by OpenAI-powered classification.
- `execute_agent_node` will be replaced by CrewAI specialist agents.
- `confidence_evaluation_node` will be replaced by a real scoring algorithm
  and human-approval policy (`backend/policy/`).
- `persist_results_node` will be replaced by repository writes to Postgres.

No node in this module performs I/O (no LLM calls, no database, no Redis).
"""

from __future__ import annotations

from backend.graph.state import (
    SupportAgentType,
    TicketCategory,
    WorkflowState,
    WorkflowStatus,
)

# Ordered (keyword, category) rules for classify_ticket_node. Order matters:
# the first matching keyword wins, so more specific terms should precede
# more general ones.
_CLASSIFICATION_RULES: tuple[tuple[str, TicketCategory], ...] = (
    ("bill", TicketCategory.BILLING),
    ("password", TicketCategory.ACCOUNT),
    ("bug", TicketCategory.TECHNICAL),
    ("error", TicketCategory.TECHNICAL),
    ("crash", TicketCategory.TECHNICAL),
)

# Category -> specialist agent. Kept as an explicit mapping (rather than
# deriving one enum from the other) so a future many-agents-per-category
# change only touches this dict.
_AGENT_BY_CATEGORY: dict[TicketCategory, SupportAgentType] = {
    TicketCategory.BILLING: SupportAgentType.BILLING_AGENT,
    TicketCategory.TECHNICAL: SupportAgentType.TECHNICAL_AGENT,
    TicketCategory.ACCOUNT: SupportAgentType.ACCOUNT_AGENT,
    TicketCategory.GENERAL: SupportAgentType.GENERAL_AGENT,
}

# Category -> human-readable agent label, used only in the placeholder
# response text generated by execute_agent_node.
_AGENT_LABEL: dict[SupportAgentType, str] = {
    SupportAgentType.BILLING_AGENT: "Billing Agent",
    SupportAgentType.TECHNICAL_AGENT: "Technical Agent",
    SupportAgentType.ACCOUNT_AGENT: "Account Agent",
    SupportAgentType.GENERAL_AGENT: "General Agent",
}


def load_ticket_node(state: WorkflowState) -> dict:
    """Placeholder ingestion step: pass the incoming ticket through unchanged.

    No database access. Future work replaces this with a repository lookup
    (`backend/database/repositories/`) that fetches the ticket by
    `ticket_id` instead of trusting the caller-supplied fields.
    """
    return {
        "ticket_id": state["ticket_id"],
        "customer_id": state["customer_id"],
        "ticket_text": state["ticket_text"],
    }


def classify_ticket_node(state: WorkflowState) -> dict:
    """Assign a `TicketCategory` via deterministic keyword matching.

    No LLM call. Future work replaces this with OpenAI-powered
    classification behind the same return contract (a `category` value).
    """
    text = state["ticket_text"].lower()
    category = TicketCategory.GENERAL
    for keyword, matched_category in _CLASSIFICATION_RULES:
        if keyword in text:
            category = matched_category
            break
    return {"category": category}


def select_agent_node(state: WorkflowState) -> dict:
    """Map `category` to the specialist agent that will handle the ticket.

    No CrewAI implementation. Future work replaces the mapping's targets
    (or adds load-balancing logic) without changing this node's contract.
    """
    category = state.get("category", TicketCategory.GENERAL)
    return {"selected_agent": _AGENT_BY_CATEGORY[category]}


def execute_agent_node(state: WorkflowState) -> dict:
    """Generate a deterministic placeholder response for `selected_agent`.

    No CrewAI invocation. Future work replaces this with a CrewAI crew
    kickoff that returns a real `draft_response` (and `retrieved_context`
    from any tools it used) using this same field contract.
    """
    agent = state.get("selected_agent", SupportAgentType.GENERAL_AGENT)
    label = _AGENT_LABEL[agent]
    return {
        "retrieved_context": None,
        "draft_response": f"Placeholder response generated by {label}.",
    }


def confidence_evaluation_node(state: WorkflowState) -> dict:
    """Placeholder confidence gate: always confident, never needs review.

    No scoring algorithm. Future work replaces these two constants with a
    real confidence score and the policy evaluation
    (`backend/policy/`) that derives `requires_human_review` from it.
    """
    return {
        "confidence_score": 1.0,
        "requires_human_review": False,
    }


def persist_results_node(state: WorkflowState) -> dict:
    """Placeholder persistence step: mark the workflow run completed.

    No Postgres/Redis access. Future work replaces this with repository
    writes (the ticket, an `AgentRun`, and an `AuditLog` row) inside a
    transaction, keeping `workflow_status` as the last field set.
    """
    return {"workflow_status": WorkflowStatus.COMPLETED}
